excluded:
  - .build
  - .dev-app

disabled_rules:
  - todo
  - trailing_whitespace
  - identifier_name
  - type_body_length

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where

line_length:
  warning: 140
  error: 220
